default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30

development:
  <<: *default
  database: 'acaidh'
  host: '127.0.0.1'
  username: 'root'
  password: '123456'
  port: 5432

test:
  <<: *default
  database: <%= ENV['DB_DATABASE_TEST'] %>
  host: <%= ENV['DB_HOST_TEST'] %>
  username: <%= ENV['DB_USERNAME_TEST'] %>
  password: <%= ENV['DB_PASSWORD_TEST'] %>
  port: 5432

production:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>