default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: 5432

production:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>