d1 = Deliveryman::create(name: 'Cololo')
d2 = Deliveryman::create(name: 'Gabriel')
d3 = Deliveryman::create(name: 'Sandrinho')
Deliveryman::create(name: 'Emmanuel')
Deliveryman::create(name: 'Julio')
Deliveryman::create(name: 'Alan')
Deliveryman::create(name: 'Ariudson')
Deliveryman::create(name: 'Edson')
Deliveryman::create(name: 'George')
Deliveryman::create(name: 'Matheus')
Deliveryman::create(name: 'Pedro Lucas')
Deliveryman::create(name: 'João Vitor')
Deliveryman::create(name: 'Jerferson')
Deliveryman::create(name: 'Gabril Coelho')

Sale::create(value: 12.00, charge: 0, payment_method: 'credit_card', delivery_method: 'in_store')
Sale::create(value: 10.00, charge: 5.00, delivery_fee: 3.00, deliveryman_id: d2.id, payment_method: 'cash', delivery_method: 'delivery')
Sale::create(value: 2.50, charge: 10.00, delivery_fee: 3.00, deliveryman_id: d3.id, payment_method: 'cash', delivery_method: 'delivery')

Expense::create(value: 12.00, kind: 'acai')
Expense::create(value: 42.00, kind: 'gasolina')
